### PR TITLE
Interpolate over autofocus pixels for sd Quattro. Fixes #89

### LINKED ISSUE #89: Black Dots Array in both tiff and dng for sd quattro
git_01

As you can see in the attached file, after I convert the x3f file to dng and zoom in to 100%, I can see black dots array in the picture when I open it in CameraRAW. If I convert the x3f into tif, the problem still exist. Is this normal?

Both the x3f and dng:
https://1drv.ms/f/s!AkqkrbwwjG27-DWWVYGNnWVrbQW5

### PR DESCRIPTION
**Pull request by erikrk**

### CODE REVIEW

**Comment by rolkar** [comment]
I will take a look at it ASAP, and run some manual tests.
I assume you have run the automatic ones?

**Comment by rolkar** [comment]
I would like the members of the struct grid_t to have more descriptive names.
Or - at least a comment per member telling what it is.

Apart from that - it looks OK.

NOTE - if there is a new camera version of sd Q or dp Q, that uses the same sensor and AF grid, then this solution will not remove the dots. They will then silently just leave them there. But, on the other hand, if there is a new image block version, then the camera is not supported, even though the code can handle it. Just a comment. Nothing really to do about that problem.

**Comment by erikrk** [comment]
I have added a comment describing the members of grid_t.

**Comment by rolkar** [comment]
If you have executed the tests, and they succeed, I think you can merge.

**Pull request merged**
